### PR TITLE
More error handling for recoverable/reconnect errors and trade

### PR DESCRIPTION
**Pull request by crubb**
See title ;)

### CODE REVIEW

**Comment by nibzo1** [comment]
Hay, good job mate.

I get a NULL pointers when the API throws and error and no data is returned 

I changed the lines where you check for data errors
`if (data.error.length) `

to 
`if (data && data.error.length) `




Also 

Line 134, we need to handle the NULL data Obj. Not sure why it is NULL, Im assuming it is to do with the Kraken API error response?


Not sure if this is correct, or if it should return a number
```
bid: data && data.result ? data.result[pair].b[0] : null,
ask: data && data.result ? data.result[pair].a[0] : null,
```

**Comment by Alexandre-io** [comment]
@crubb @nibzo1 I had to refactor the error matching, could you please check if it works as expected ?

**Comment by nibzo1** [comment]
@Alexandre-io this seems to trade now for me and I dont seem to have many errors, The bot has been running for 14hrs now and execute about 8 trades with my config.

All look to be good trades too :+1: 

Ill look at my log and see what exactly it has done in more detail

**Comment by crubb** [comment]
@Alexandre-io Working. I'm still running into quite a few timeout errors, I just increased the timeoutMS of the kraken-api 0.1.7 from 5s to 10s.

There is still the "Too many API calls" error I referenced in https://github.com/carlos8f/zenbot/issues/177

and sometimes I get `Order:Order minimum not met` (I only put like 0.1 ETH on kraken)

**Comment by nibzo1** [comment]
Yes I see the timeout error too, Does the kraken-api 0.1.7  timeout update fix it?

Also does it fix the 

`Kraken API is down! unable to call getBalance, retrying in 2.5s`

**Pull request merged**
