### PR TITLE
More verbose retries & adjusted min product order size

### PR DESCRIPTION
**Pull request by crubb**
Not much from me tonight ;)

- Our merges are now conflicting due to different timeouts on the retry - I propose to set the timeout to 2.5s. I could vastly reduce the timeout errors by adjusting the `config.timeoutMS` in https://github.com/nothingisdead/npm-kraken-api/blob/master/kraken.js#L20 to 10000. The module seems to be unmaintained, what do you suggest?

- Adjusted minimum order size according to https://support.kraken.com/hc/en-us/articles/205893708-What-is-the-minimum-order-size-

### CODE REVIEW

**Comment by crubb** [comment]
Sorry, I had merged my tree with the latest master from https://github.com/carlos8f/zenbot (no conflicts) - Seems to be working fine for, but I forgot when I pushed the latest changes. Do you want me to split it up?

**Comment by Alexandre-io** [comment]
@crubb @nibzo1 thanks!, I was unable to squash all commits into one for the PR, so I created a new branch feat-kraken (https://github.com/Alexandre-io/zenbot/tree/feat-kraken)

**Comment by crubb** [comment]
?

I could create a PR from my branch to https://github.com/carlos8f/zenbot with no problems? It will show as multiple commits, yes, but that way @nibzo1 and my contributions are properly attributed. I think that's the way git/GitHub works when merging branches from multiple contributors.

**Comment by crubb** [comment]
Thank you for https://github.com/carlos8f/zenbot/pull/207, @Alexandre-io, much appreciated ;)

**Comment by Alexandre-io** [comment]
You are welcome ;)

**Pull request merged**
